Topic/vererbung und polymorphie
jfuerlinger/maturavorbereitung-2020_21 pull request #14
Opened 2021-01-28 12:41 UTC by DominikJonke

String interpolation wurde implementiert.

2021-02-11 08:57 UTC, jfuerlinger requested changes
Bitte diese Unsauberkeiten noch bereinigen.

2021-02-11 08:57 UTC, jfuerlinger commented on vererbung_und_polymorphie/README.md
> +        return $"{abheben}";
Adaptierung auf `return "abheben";`.

2021-02-11 08:57 UTC, jfuerlinger commented on vererbung_und_polymorphie/README.md
> +        return $"{passagiermaschine}" + base.Abheben();
Adaptierung auf `return $"{passagiermaschine} {base.Abheben()}";`.

2021-02-11 08:57 UTC, jfuerlinger commented on vererbung_und_polymorphie/README.md
> +        return $"{zeppelin}" + base.Abheben();
Adaptierung auf `return $"{zeppelin} {base.Abheben()}";`.

2021-02-11 08:57 UTC, jfuerlinger commented on vererbung_und_polymorphie/README.md
> +        return string.Format($"{ballon}");
Adaptierung auf `return "ballon";`.

2021-02-11 08:57 UTC, jfuerlinger commented on vererbung_und_polymorphie/README.md
> +        return $"{auto}";
Adaptierung auf `return auto;`.

2021-02-11 08:57 UTC, jfuerlinger commented on vererbung_und_polymorphie/README.md
> +    string fahrrad = "Es ist ein Fahrrad.");
Compile-Error!

2021-02-11 08:57 UTC, jfuerlinger commented on vererbung_und_polymorphie/README.md
> +        return base.Method() + $"{motorrad}";
Adaptierung auf `return $"{base.Methode()} {motorrad}";`.

2021-02-11 08:57 UTC, jfuerlinger commented on vererbung_und_polymorphie/README.md
> +        return string.Format($"{fahrrad}");
Adaptierung auf `return fahrrad;`.

2021-02-11 16:26 UTC, DominikJonke commented
Wurde behoben.

2021-03-05 13:10 UTC, jfuerlinger approved these changes
Passt jetzt für mich 👍

2021-03-05 13:12 UTC, merged