Topic/ef validation
jfuerlinger/maturavorbereitung-2020_21 pull request #18
Opened 2021-02-09 12:06 UTC by JanineHoellhuber

Fertige Ausarbeitung

2021-02-11 08:43 UTC, jfuerlinger requested changes
Sieht schon gut aus 💪

2021-02-11 08:43 UTC, jfuerlinger commented on ef-validation/README.md
> +    * ValidationExecption zum Transport von Exceptions
Typo!

2021-02-11 08:43 UTC, jfuerlinger commented on ef-validation/README.md
> +        return new RegularExpressionAttribute(@"^[+0]\d+").IsValid(Convert.ToString(value).Trim());
Dieses Beispiel ist nicht optimal - es gibt ja ein eigenes [RegularExpressionAttribute ](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.regularexpressionattribute?view=net-5.0) welche Regular Expressions validiert.

Sie könnten in diesem Beispiel eine SVNr-Validierung implementieren. Den Beispielcode der Validierung müssen sie für das Verständnis nicht komplett ausimplementieren.

2021-02-11 08:43 UTC, jfuerlinger commented on ef-validation/README.md
> +            throw new ValidationException(new ValidationResult($"Produkt mit den Namen {product.Name} existiert bereits", new List<string> {"Isbn"}),
Zusammenhäng erklären warum hier der PropertyName `Isbn` beim ValidationResult-Constructor übergeben wird.

2021-02-11 08:43 UTC, jfuerlinger commented on ef-validation/README.md
> +        && b.Price == product.Price))
Warum wird hier auch der Preis auf Gleichheit geprüft -> die Meldung sagt ja aus, dass das Produkt mit diesem Namen schon existiert.

2021-02-11 08:43 UTC, jfuerlinger commented on ef-validation/README.md
> +        if (await _dbContext.Products.AnyAsync(b => b.Id == product.Id &&
Die IDs hier zu vergleichen macht keinen Sinn - es geht mMn darum, dass der Name von zwei "unterschiedlichen" Produkten gleich ist, was nicht zulässig ist.

2021-02-11 08:43 UTC, jfuerlinger commented on ef-validation/README.md
> +* HasErrors (Property):
Für das Verständnis wäre es gut hier den Code anzufügen:

```c#
public bool HasErrors { get; }
```

Bitte auch bei den anderen Methoden/Properties

2021-02-11 08:43 UTC, jfuerlinger commented on ef-validation/README.md
> +* Wichtig ist zudem auch den UpdateSourceTrigger auf PropertyChanged zu setzen um nach jedem Zeichen die Eingabe zu validieren.
Bitte Source-Fragmente entsprechend zu formatieren:

Wichtig ist zudem auch den `UpdateSourceTrigger` auf `PropertyChanged` zu setzen um nach jedem Zeichen die Eingabe zu validieren.

2021-02-11 08:43 UTC, jfuerlinger commented on ef-validation/README.md
> +* Sollten Fehler auftreten werden diese einem ViewModel-Property (DbError) zugewiesen, welches am Window gebunden ist.
Einerseits wird die Eigenschaft `DbError` mit der Fehlermeldung versorgt (hier bitte noch den Hinweis, dass im UI ein `Control` dagegen gebunden werden muss!).

Andererseits werden auch per `Errors.Add(...)` Fehlermeldungen direkt beim `UI-Control` angezeigt. Auf diesen Punkt noch eingehen!

2021-02-11 08:43 UTC, jfuerlinger commented on ef-validation/README.md
> +        * ...
Diesen Punkt verstehe ich noch nicht ganz!

2021-02-11 08:43 UTC, jfuerlinger commented on ef-validation/README.md
> +* Sie wird zur Validierung der einzelnen Properties verwendet.
... verwendet und stellt eine Alternative zur Validierung per Validierungunsattribute in den Modellklassen dar!

2021-02-11 08:43 UTC, jfuerlinger commented on ef-validation/README.md
> +        yield return new ValidationResult("Lastname is required",new string[] { nameof(Lastname) });
Wenn hier `yield` verwendet wird, so bitte kurz drauf eingehen.

2021-02-11 08:43 UTC, jfuerlinger commented on ef-validation/README.md
> +    * Web-UI clientseitig -> Validierung im Browser
Hierzu sollte unten noch ein Beispiel angeführt werden was im Razor-Code notwendig ist.

z.B.:

```asp.net
<input asp-for="Participant.Firstname" class="form-control">
<span asp-validation-for="Participant.Firstname"></span>
```

2021-02-14 09:51 UTC, JanineHoellhuber commented on ef-validation/README.md
> +    * ValidationExecption zum Transport von Exceptions
Was genau meinen Sie damit?

2021-02-14 10:00 UTC, JanineHoellhuber commented on ef-validation/README.md
> +        if (await _dbContext.Products.AnyAsync(b => b.Id == product.Id &&
Ich dachte man muss die ID immer vergleichen, da Sie es bei ihrem Bakery Beispiel auch die ID vom Produkt verglichen haben.

2021-03-02 15:07 UTC, JanineHoellhuber commented
Wurde geändert.

2021-03-05 13:06 UTC, jfuerlinger commented on ef-validation/README.md
> +    * ValidationExecption zum Transport von Exceptions
Typo = Rechtschreibfehler:

![image](https://user-images.githubusercontent.com/44121556/110119333-f7855980-7dbb-11eb-9682-fe22255686cf.png)

2021-03-05 13:09 UTC, jfuerlinger approved these changes
Passt für mich - gut gemacht 👍

2021-03-05 13:09 UTC, merged