Topic/linq kolev
jfuerlinger/maturavorbereitung-2020_21 pull request #19
Opened 2021-02-11 09:47 UTC by zvonkokolev

first draft

2021-02-19 10:17 UTC, jfuerlinger requested changes
Schaut super aus 💪

Haben Sie viel aus den Quellen übernommen?

2021-02-19 10:17 UTC, jfuerlinger commented on LINQ/README.md
> +```sh
Verwenden sie bitte "csharp" und nicht "sh"

2021-02-19 14:21 UTC, zvonkokolev commented on LINQ/README.md
> +```sh
Damit die Kollegen was gescheites lernen können (alles andere wäre eine Katastrophe).

2021-03-05 13:03 UTC, jfuerlinger commented
Das war ein super Referat!! 🎉

2021-03-05 13:05 UTC, jfuerlinger approved these changes

2021-03-05 13:05 UTC, merged