Topic/rest gutenbrunner
jfuerlinger/maturavorbereitung-2020_21 pull request #20
Opened 2021-02-15 16:46 UTC by MIGU-1

Ready for check ;)

2021-02-19 10:08 UTC, jfuerlinger requested changes
Sie haben REST schon sehr gut erklärt, allerdings sollte es sich in diesem Referat hauptsächlich um die Implementierung einer REST-Applikation mithilfe von ASP.NET Core WebAPI drehen:

![image](https://user-images.githubusercontent.com/44121556/108490044-8f565400-72a2-11eb-9daf-7deeb3413d10.png)

Erklären Sie die Konzepte dort (Controllers, Routing, Swagger, etc.) anhand von Beispielen:

2021-02-19 10:08 UTC, jfuerlinger commented on README.md
> +# REST-API Prinzipien?
warum mit "?"

2021-02-19 10:08 UTC, jfuerlinger commented on README.md
> +  - Jede REST-Nachricht enthält alle Informationen, die für den Server bzw. Client notwendig sind, um die Nachricht zu verstehen. Weder der Server noch die Anwendung soll Zustandsinformationen zwisch
Meines Wissens nach muss nur der Server zustandslos sein?!

2021-02-19 10:08 UTC, jfuerlinger commented on README.md
> +Die Browserapplikation generiert den Request and Webserver mit der entsprechenden HTTP-Methode.
Neben dem Browser, welcher die Requests generiert würde ich hier noch andere Komponenten nennen (z.B. eine CLI, welche eine REST-API, verwendet, oder eine WPF-Applikation, welche eine SMS-API verwendet).

2021-02-19 10:08 UTC, jfuerlinger commented on README.md
> +Die Requestdaten werden befinden sich im Header.
Was zählt alles zu den Requestdaten (Beispiele)?

2021-02-19 10:08 UTC, jfuerlinger commented on README.md
> +Content-Type: application/json
`Content-Type` erklären

2021-02-19 10:08 UTC, jfuerlinger commented on README.md
> +Nach erhalt der Anfrage wird diese vom Webserver verarbeitet, indem er die gewünschten Aktionen unter Sicherheitsanforderungen umsetzt.
Typo -> "erhalt"

2021-02-22 14:31 UTC, MIGU-1 commented
Implementierung hinzugefügt

2021-02-26 09:17 UTC, jfuerlinger approved these changes

2021-02-26 09:18 UTC, merged

2021-02-26 09:22 UTC, jfuerlinger commented
@MIGU-1 was mir gerade aufgefallen ist: Sie haben meine README.md mit ihrem Referat überschrieben!

Bitte ihre Anpassungen in der README.md ihres Unterordners vornehmen!