Topic/interfaces aichmayr
jfuerlinger/maturavorbereitung-2020_21 pull request #8
Opened 2021-01-12 17:02 UTC by SimonAi1801

Habe einige Punkte bearbeitet. Bitte um kurze Kontrolle.

2021-01-22 09:48 UTC, jfuerlinger requested changes
Passt schon fast - einige Kleinigkeiten habe ich angemerkt.

2021-01-22 09:48 UTC, jfuerlinger commented on Interfaces-Aichmayr/README.md
> +- Eine Schnittstelle enhält keinen Implementierung von Methoden
Bitte kurz hierauf eingehen:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods

2021-01-22 09:48 UTC, jfuerlinger commented on Interfaces-Aichmayr/README.md
> +- Eine Schnittstelle kann von einer oder mehreren Schnittstellen erben
nicht erben -> erweitern

2021-01-22 09:48 UTC, jfuerlinger commented on Interfaces-Aichmayr/README.md
> +
Bitte noch auf explizite vs implizite Implementierung von Interfaces eingehen:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation

2021-02-04 12:59 UTC, SimonAi1801 commented on Interfaces-Aichmayr/README.md
> +- Eine Schnittstelle kann von einer oder mehreren Schnittstellen erben
Wurde erledigt.

2021-02-04 13:01 UTC, SimonAi1801 commented on Interfaces-Aichmayr/README.md
> +- Eine Schnittstelle enhält keinen Implementierung von Methoden
Bin mir nicht gtanz sicher auf was ich genau eingehen soll.

2021-02-04 13:27 UTC, SimonAi1801 commented on Interfaces-Aichmayr/README.md
> +
Sollte passen.

2021-02-04 13:28 UTC, SimonAi1801 commented
Bitte um Kontrolle

2021-02-11 09:03 UTC, jfuerlinger commented on Interfaces-Aichmayr/README.md
> +- Eine Schnittstelle enhält keinen Implementierung von Methoden
Dabei gehts darum, dass sich ein `Interface` im Laufe der Zeit verändern kann. ZB. könnten neue Methoden dazukommen, welche im Vertrag gefordert werden.

Nun gibt es Bestandscode welcher dieses Interface implementiert. Wenn dieser nun (inkl. der neuen Methode im Interface) neu kompiliert werden würde, so würden natürlich Compile-Errors entstehen.

Damit das nicht passiert, kann der `Interface`-Autor eine "Standard-Implementierung" zum Interface hinzufügen.

Das ist mit C# 8.0 dazugekommen - vielleicht schreiben Sie einen Absatz darüber.

2021-02-11 09:12 UTC, jfuerlinger requested changes
Sieht schon gut aus 💪

2021-02-11 09:12 UTC, jfuerlinger commented on Interfaces-Aichmayr/README.md
> +- Eine Schnittstelle kann von einer oder mehreren Schnittstellen erben
Ich siehe die Änderung noch nicht?!

![image](https://user-images.githubusercontent.com/44121556/107617687-a8328a00-6c50-11eb-9ba2-9d44c7c71db3.png)

2021-02-11 09:12 UTC, jfuerlinger commented on Interfaces-Aichmayr/README.md
> +- Beim Implementieren der Klasse ist die spatere Verwendung nicht von Bedeutung, sondern nur die bereitzustellende Funktionälitat
Typo!

2021-02-11 09:12 UTC, jfuerlinger commented on Interfaces-Aichmayr/README.md
> +```
Bitte Code immer für C# formatieren:

![image](https://user-images.githubusercontent.com/44121556/107617850-e6c84480-6c50-11eb-9bdc-c516afb3e8ec.png)


```C#
public interface ICopy() {}
```

2021-02-11 09:12 UTC, jfuerlinger commented on Interfaces-Aichmayr/README.md
> +- Klassenname und Vererbungshierarchie der konkreten Implementierung ist egal
Zusätzlich erhöht sich die Testbarkeit, da einzelne Komponenten wie zB. ein Repository leicht "gefaked" werden können.

Statt Zugriff auf die Datenbank nutzt die Fake-Implementierung des Repositories nur ein internes Array für die Datenspeicherung.

2021-02-11 09:12 UTC, jfuerlinger commented on Interfaces-Aichmayr/README.md
> +| Prüfung         | Prüfung zur Komplierzeit                                                 | Prüfung zur Komplierzeit                                                  |
"Prüfung während der Kompilierung"

2021-02-11 09:12 UTC, jfuerlinger commented on Interfaces-Aichmayr/README.md
> +| Implementierung | Können implementierungen enthalten                                       | Enthalten keine implementierungen (lediglich deklarationen)               |
implementierungen groß schreiben!

2021-02-16 16:21 UTC, SimonAi1801 commented on Interfaces-Aichmayr/README.md
> +```
Erledigt

2021-02-16 16:22 UTC, SimonAi1801 commented on Interfaces-Aichmayr/README.md
> +| Implementierung | Können implementierungen enthalten                                       | Enthalten keine implementierungen (lediglich deklarationen)               |
Erledigt

2021-02-16 16:26 UTC, SimonAi1801 commented on Interfaces-Aichmayr/README.md
> +- Klassenname und Vererbungshierarchie der konkreten Implementierung ist egal
Done

2021-02-16 16:30 UTC, SimonAi1801 commented on Interfaces-Aichmayr/README.md
> +- Beim Implementieren der Klasse ist die spatere Verwendung nicht von Bedeutung, sondern nur die bereitzustellende Funktionälitat
Alles klar

2021-02-17 09:05 UTC, SimonAi1801 commented on Interfaces-Aichmayr/README.md
> +| Prüfung         | Prüfung zur Komplierzeit                                                 | Prüfung zur Komplierzeit                                                  |
erledigt

2021-02-19 10:10 UTC, jfuerlinger approved these changes
Passt jetzt - super 👍

2021-02-19 10:11 UTC, merged